project: 
  type: website
  output-dir: _site

website: 
  page-navigation: true
  title: "NOAA quarto simple" 
  site-url: "https://github.com/shannonrankin/open-science-dashboard" 
  repo-url: "https://shannonrankin.github.io/open-science-dashboard/"
  repo-actions: [edit, source, issue]
  favicon: images/favicon.ico
  
  page-footer:
    right: "This page is built with [Quarto](https://quarto.org/)."
    left: "&copy; CC-1.0"
  
  sidebar:
    background: "#D9E3E4"
    logo: "https://upload.wikimedia.org/wikipedia/commons/7/79/NOAA_logo.svg"
    favicon: images/favicon.ico
    pinned: true
    align: center
    tools: 
      - icon: globe
        href: https://shannonrankin.github.io/open-science-dashboard/
        text: "Open Science Dashboard"
      - icon: github
        href: https://github.com/shannonrankin/open-science-dashboard
        text: "Open Science Dashboard"

    style: "docked"
    search: true
    collapse-level: 1
    contents:
      - href: index.qmd
        text: Home
      - href: content/dashboard.qmd
        text: "Open Science Dashboard"
      - href: content/dashboard-givingBack.qmd
        text: Submit Example to Dashboard
      - href: content/Instructions.qmd
        text: How To

        
format:
  html:
    theme:
      light: [cosmo, theme.scss] 
      dark: [cosmo, theme-dark.scss]
    code-copy: true
    code-overflow: wrap
    toc: true

resources:
  - content/card-images/*

filters:
  - include-files.lua
  - quarto

  
